#BSUB -J cgpack
#BSUB -oo zzz.out
#BSUB -eo zzz.err
#BSUB -P HCT00036
#BSUB -R "span[ptile=24]"
#BSUB -W 0:19
#BSUB -n 72

#$Id: job.ibm.lsf 310 2016-06-30 10:10:48Z mexas $
#  AUTHOR
#    Anton Shterenlikht
#  COPYRIGHT
#    See LICENSE
#  DESCRIPTION
#    A job submission script for the IBM LSF scheduler

# Change to the submission directory
cd $LS_SUBCWD
echo $LS_SUBCWD

EXECUTABLE=testABW.x
CACONFILE=xx14.conf
NODES=nodes

# Specify the desired Intel MPI fabric here, or leave empty for default
# See https://software.intel.com/en-us/node/535585
#FABRIC=
#FABRIC="I_MPI_FABRICS=shm:dapl"
#FABRIC="I_MPI_FABRICS=shm:tcp"

# Load Intel modules
. /etc/profile.d/modules.sh
module purge
module add intel_mpi
module list

# How many processors are allocated.
# Save all nodes to file $NODES
rm $NODES
NP=0
for TOKEN in $LSB_HOSTS
do
	(( NP++ ))
	echo $TOKEN >> $NODES
done 

# Prepare conf file
echo -genvall -genv $FABRIC -machinefile ./$NODES -n $NP ./$EXECUTABLE > $CACONFILE

# Use the full path name
$LS_SUBCWD/$EXECUTABLE
